#!/bin/bash

NAME=sample
NUMBER_OF_MACHINE=$NB_MACHINE

docker_ip=$(docker-machine ip dev)
#docker_ip=127.0.0.1

port=$(docker port ${NAME}_client_1 22| sed 's/.*://')
machine_host="${machine_host} \"client\": {\"ansible_ssh_host\": \"$docker_ip\", \"ansible_ssh_port\": \"$port\"}, "

i=1
while [ $i -lt $NUMBER_OF_MACHINE ]
do
    replica_name="${replica_name} \"replica_$i\", "
    port=$(docker port ${NAME}_replica_$i 22| sed 's/.*://')
    machine_host="${machine_host} \"replica_$i\": {\"ansible_ssh_host\": \"$docker_ip\", \"ansible_ssh_port\": \"$port\"}, "
    i=$[$i+1]
done

replica_name="${replica_name} \"replica_$NUMBER_OF_MACHINE\""
port=$(docker port ${NAME}_replica_$NUMBER_OF_MACHINE 22| sed 's/.*://')
machine_host="${machine_host} \"replica_$NUMBER_OF_MACHINE\": {\"ansible_ssh_host\": \"$docker_ip\", \"ansible_ssh_port\": \"$port\"}"

cat << EOF
{
  "client": {
    "hosts": [ "client" ]
  },
  "replica-rs0": {
    "hosts": [ $replica_name ]
  },
  "replica-rs1": {
    "hosts": [ $replica_name ]
  },
  "commons": {
    "children": ["client", "replica-rs0", "replica-rs1"]
  },
  "env": {
    "children": ["commons"]
  },
  "_meta": {
    "hostvars": {
      $machine_host
    }
  }
}
EOF
