#!/bin/bash

NAME=sample
NUMBER_OF_MACHINE=$NB_MACHINE

docker_ip=$(docker-machine ip dev)

port=$(docker port ${NAME}_client_1 22| sed 's/.*://')
machine_host="${machine_host} \"client\": {\"ansible_ssh_host\": \"$docker_ip\", \"ansible_ssh_port\": \"$port\"}, "

i=1
while [ $i -lt $NUMBER_OF_MACHINE ]
do
    server="${server} \"server_$i\", "
    port=$(docker port ${NAME}_server_$i 22| sed 's/.*://')
    machine_host="${machine_host} \"server_$i\": {\"ansible_ssh_host\": \"$docker_ip\", \"ansible_ssh_port\": \"$port\"}, "
    i=$[$i+1]
done

server="${server} \"server_$NUMBER_OF_MACHINE\""
port=$(docker port ${NAME}_server_$NUMBER_OF_MACHINE 22| sed 's/.*://')
machine_host="${machine_host} \"server_$NUMBER_OF_MACHINE\": {\"ansible_ssh_host\": \"$docker_ip\", \"ansible_ssh_port\": \"$port\"}"

cat << EOF
{
  "client": {
    "hosts": [ "client" ]
  },
  "server": {
    "hosts": [ $server ]
  },
  "commons": {
    "children": [ "client", "server" ]
  },
  "env": {
    "children": [ "commons" ]
  },
  "_meta": {
    "hostvars": {
      $machine_host
    }
  }
}
EOF
