---
- name: Copy the file /script/config_status.js
  template:
    src: "config_status.j2"
    dest: "/script/config_status.js"

- name: Copy the file /script/config_init.js
  template:
    src: "config_init.j2"
    dest: "/script/config_init.js"

- name: Check the config status
  shell: "/opt/mongodb/bin/mongo --host {{hostvars[groups['config'][0]]['ansible_nodename']}} --port {{config.port}} /script/config_status.js"
  register: st
  changed_when: st.stdout.find("already initialized") == -1

- name: Initialize the config
  shell: "/opt/mongodb/bin/mongo --host {{hostvars[groups['config'][0]]['ansible_nodename']}} --port {{config.port}} /script/config_init.js"
  when: st.stdout.find("already initialized") == -1
  register: log

- name: Show config log
  debug:
    var: log.stdout_lines
  when: st.stdout.find("already initialized") == -1
