---
- name: Create the data directory for replicaset
  file:
    path=/data/db-{{replica_name}}
    owner=mongod
    group=mongod
    state=directory
  become: yes

- name: Create the replicaset file
  template: src=mongod.conf.j2 dest=/etc/mongodb-{{replica_name}}.conf
  become: yes

- name: Check process replicaset
  shell: ps -auxww | grep /etc/mongodb-{{replica_name}}.conf
  register: ps
  changed_when: ps.stdout_lines|length <= 2

- name: Run replicaset
  shell: ./mongod --config /etc/mongodb-{{replica_name}}.conf
  args:
    chdir: /opt/mongodb/bin
  when: ps.stdout_lines|length <= 2
  become: yes
  become_user: mongod
