---
- name: Create the file to initialize the mongod replica set
  template:
    src: "{{item}}.j2"
    dest: "/tmp/{{item}}.js"
  with_items:
    - sharding_init
    - sharding_status

#- name: Check the sharding status
#  shell: "/opt/mongodb/bin/mongo --host {{hostvars['sharding']['ansible_nodename']}} /tmp/repset_status.js"
#  register: st
#  changed_when: st.stdout.find("already initialized") == -1

- name: Initialize the sharding
  shell: "/opt/mongodb/bin/mongo {{hostvars['sharding']['ansible_nodename']}}:27017/admin /tmp/sharding_init.js"
  when: st.stdout.find("already initialized") == -1
  register: log_mongo

- name: Show sharding log
  debug:
    var: log_mongo.stdout_lines
  when: st.stdout.find("already initialized") == -1
