---
- name: Create the file to initialize the mongod replica set
  template:
    src: "sharding_status.j2"
    dest: "/script/sharding_status.js"

- name: Create the file to initialize the mongod replica set
  template:
    src: "sharding_init.j2"
    dest: "/script/sharding_init_{{item.name}}.js"
  with_items: "{{replica}}"

- name: Initialize the sharding
  shell: "/opt/mongodb/bin/mongo {{hostvars['sharding']['ansible_nodename']}}/admin /script/sharding_init_{{item.name}}.js"
  register: log_mongo
  with_items: "{{replica}}"

- name: Show sharding log
  debug:
    var: log_mongo.results[item.0].stdout_lines
  with_indexed_items: "{{replica}}"
