---
workspace: /tmp/ansible
config:
  name: configReplSet
  port: 27019
sharding:
  chunkSize: 1
proxy_env:
  https_proxy: http://pcyvipncp2n.edf.fr:3128/
  http_proxy: http://pcyvipncp2n.edf.fr:3128/
  no_proxy: localhost
