---
- name: Change /etc/hosts
  shell: "
      if grep \"{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['ansible_nodename'] }}\" /etc/hosts;
      then echo 0;
      else echo \"{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['ansible_nodename'] }}\" >> /etc/hosts;
      fi
    "
  register: st
  changed_when: st.stdout == ""
  with_items: "{{ groups[machines] | difference(inventory_hostname) }}"
  become: yes
