---
- get_url:
    url: "{{kafka_url}}"
    mode: 0644
    force: no
    validate_certs: no
    dest: "{{workspace}}/{{kafka_name}}.tgz"
  delegate_to: localhost
  run_once: true

- stat: path="/opt/kafka"
  register: st
  become: yes

- unarchive:
    src: "{{workspace}}/{{kafka_name}}.tgz"
    dest: "/opt"
  become: yes
  when: not st.stat.exists

- file:
    src: "/opt/{{kafka_name}}"
    dest: "/opt/kafka"
    state: link
  become: yes

- lineinfile:
    dest: "/home/deploy/.bashrc"
    line: 'export PATH=$PATH:/opt/kafka/bin'
    insertafter: 'EOF'
    regexp: 'export PATH=\$PATH:/opt/kafka/bin'
    state: present
