---
- name: Change mode /var
  file:
    path=/var
    mode=777
  become: yes

- name: Change mode /var/log
  file:
    path=/var/log
    mode=777
  become: yes

- name: Create the mongod user
  user:
    name=mongod
  become: yes

- name: Create the mongod group
  group:
    name=mongod
  become: yes

- name: Install mongodb
  unarchive:
    src=mongodb-linux-x86_64-3.0.8.tgz
    dest=/opt
    owner=mongod
    group=mongod
  become: yes

- name: Create symlink /opt/mongodb
  file:
    src=/opt/mongodb-linux-x86_64-3.0.8
    dest=/opt/mongodb
    owner=mongod
    group=mongod
    state=link
  become: yes

- name: Create the data directory for the namenode metadata
  file:
    path=/data/db
    owner=mongod
    group=mongod
    state=directory
  become: yes

- name: Run MongoDB
  shell: ./mongod --port 12345 --fork --logpath /var/log/mongodb.log --dbpath /data/db/
  args:
    chdir: /opt/mongodb/bin
  register: st
  changed_when: st.stdout.find("child process started successfully") == -1
  failed_when: false
  become: yes
  become_user: mongod
