FROM centos:7

ENV http_proxy=http://CB1791DN@noevipncp2n.edf.fr:3128/
ENV https_proxy=https://CB1791DN@noevipncp2n.edf.fr:3128/
ENV no_proxy="localhost,192.168.99.100,127.0.0.1,.local,.edf.fr,.erdf.fr"
