---
- name: Create the data directory
  file:
    path=/data
    state=directory
    mode=777
  become: yes

- name: Create the zookeeper conf directory
  file:
    path=/opt/zookeeper-3.4.8/conf
    state=directory
  become: yes

- name: Create the zoo.cfg file
  template: src=zoo.cfg.j2 dest=/opt/zookeeper-3.4.8/conf/zoo.cfg
  become: yes

- name: Create the myid file
  template: src=myid.j2 dest=/data/myid
  become: yes

- name: Launch zookeeper
  shell: zkServer.sh restart
  register: log

- name: Show log
  debug:
    var: log
