---
- name: Change mode /var
  file:
    path=/var
    mode=777
  become: yes

- name: Change mode /var/log
  file:
    path=/var/log
    mode=777
  become: yes

- name: Create the data directory for the namenode metadata
  file:
    path=/data/db
    owner=mongod
    group=mongod
    state=directory
  become: yes

- name: Create the mongodb configuration file
  template: src=mongod.conf.j2 dest=/etc/mongodb.conf
  become: yes

- name: Check process mongod
  shell: ps -auxww | grep mongod
  register: ps
  changed_when: ps.stdout_lines|length <= 2

- name: Run MongoDB
  shell: ./mongod --config /etc/mongodb.conf
  args:
    chdir: /opt/mongodb/bin
  register: st
  when: ps.stdout_lines|length <= 2
  become: yes
  become_user: mongod
