---
# Gather facts to be able to use them in next plays
- hosts: all
  gather_facts: yes
  remote_user: deploy

- hosts: all
  gather_facts: no
  remote_user: deploy
  roles:
    - { role: etc_hosts }

- hosts: client
  gather_facts: no
  remote_user: deploy
  roles:
    - { role: jdk, tags: [jdk] }
    - { role: zookeeper/install, tags: [zookeeper] }

- hosts: server
  gather_facts: no
  remote_user: deploy
  roles:
    - { role: jdk, tags: [jdk] }
    - { role: zookeeper/install, tags: [zookeeper] }
    - { role: zookeeper/server, tags: [zookeeper] }
