---
- group:
    name: deploy
    state: present
  become: yes
- user:
    name: deploy
    group: deploy
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  become: yes
- fetch: src=/home/deploy/.ssh/id_rsa.pub dest={{workspace}}/fetch
  become: yes
- authorized_key:
    user: deploy
    key: "{{ lookup('file', '{{workspace}}/fetch/{{inventory_hostname}}/home/deploy/.ssh/id_rsa.pub') }}"
  become: yes
- authorized_key:
    user: deploy
    key: "{{public_ssh_key}}"
  become: yes
- copy:
    src: sudoers_prerequis
    dest: /etc/sudoers.d/sudoers_prerequis
    owner: root
    group: root
    mode: 0440
    backup: yes
    validate: '/usr/sbin/visudo -cf %s'
  become: yes
- file:
    path: "{{workspace}}"
    state: directory
  delegate_to: localhost
  run_once: true
